
SET SEARCH_PATH = "VENTE_ODS";

-- affichage des tables

SELECT *
FROM "ODS_CLIENT";


SELECT *
FROM "VENTE_ODS"."ODS_TYPE_CLIENT";


SELECT *
FROM "VENTE_ODS"."ODS_PRODUIT";


SELECT *
FROM "VENTE_ODS"."ODS_SOUS_CATEGORIE";


SELECT *
FROM "VENTE_ODS"."ODS_CATEGORIE";


SELECT *
FROM "VENTE_ODS"."ODS_VENTE";


SELECT *
FROM "VENTE_ODS"."ODS_REJET";

-- Tableau plus général

SELECT
	"VENTE_ODS"."ODS_VENTE"."ID_VENTE",
	"VENTE_ODS"."ODS_VENTE"."DT_VENTE",
	"VENTE_ODS"."ODS_PRODUIT"."NOM_PRODUIT",
	"VENTE_ODS"."ODS_VENTE"."QTE_VENTE",
	"VENTE_ODS"."ODS_VENTE"."PRIX_VENTE",
	"VENTE_ODS"."ODS_VENTE"."PRIX_ACHAT",
	"VENTE_ODS"."ODS_CLIENT"."ID_CLIENT",
	"VENTE_ODS"."ODS_CLIENT"."VILLE_CLIENT",
	"VENTE_ODS"."ODS_CLIENT"."PAYS_CLIENT",
	"VENTE_ODS"."ODS_CLIENT"."REGION_CLIENT",
	"VENTE_ODS"."ODS_SOUS_CATEGORIE"."LB_SOUS_CATEGORIE"
FROM "VENTE_ODS"."ODS_VENTE"
LEFT JOIN "VENTE_ODS"."ODS_PRODUIT" ON "VENTE_ODS"."ODS_VENTE"."CD_PRODUIT" = "VENTE_ODS"."ODS_PRODUIT"."CD_PRODUIT"
LEFT JOIN "VENTE_ODS"."ODS_CLIENT" ON "VENTE_ODS"."ODS_VENTE"."ID_CLIENT" = "VENTE_ODS"."ODS_CLIENT"."ID_CLIENT"
LEFT JOIN "VENTE_ODS"."ODS_SOUS_CATEGORIE" ON "VENTE_ODS"."ODS_PRODUIT"."CD_SOUS_CATEGORIE" = "VENTE_ODS"."ODS_SOUS_CATEGORIE"."CD_SOUS_CATEGORIE";


-- création table à partir de cette requête
DROP TABLE IF EXISTS "VENTE_ODS"."TABLEAU_SYNTHESE";

CREATE TABLE "VENTE_ODS"."TABLEAU_SYNTHESE" AS
SELECT
	"VENTE_ODS"."ODS_VENTE"."ID_VENTE",
	"VENTE_ODS"."ODS_VENTE"."DT_VENTE",
	"VENTE_ODS"."ODS_PRODUIT"."NOM_PRODUIT",
	"VENTE_ODS"."ODS_VENTE"."QTE_VENTE",
	"VENTE_ODS"."ODS_VENTE"."PRIX_VENTE",
	"VENTE_ODS"."ODS_VENTE"."PRIX_ACHAT",
	"VENTE_ODS"."ODS_CLIENT"."ID_CLIENT",
	"VENTE_ODS"."ODS_CLIENT"."VILLE_CLIENT",
	"VENTE_ODS"."ODS_CLIENT"."PAYS_CLIENT",
	"VENTE_ODS"."ODS_CLIENT"."REGION_CLIENT",
	"VENTE_ODS"."ODS_SOUS_CATEGORIE"."LB_SOUS_CATEGORIE"
FROM "VENTE_ODS"."ODS_VENTE"
LEFT JOIN "VENTE_ODS"."ODS_PRODUIT" ON "VENTE_ODS"."ODS_VENTE"."CD_PRODUIT" = "VENTE_ODS"."ODS_PRODUIT"."CD_PRODUIT"
LEFT JOIN "VENTE_ODS"."ODS_CLIENT" ON "VENTE_ODS"."ODS_VENTE"."ID_CLIENT" = "VENTE_ODS"."ODS_CLIENT"."ID_CLIENT"
LEFT JOIN "VENTE_ODS"."ODS_SOUS_CATEGORIE" ON "VENTE_ODS"."ODS_PRODUIT"."CD_SOUS_CATEGORIE" = "VENTE_ODS"."ODS_SOUS_CATEGORIE"."CD_SOUS_CATEGORIE";


SELECT *
FROM "VENTE_ODS"."TABLEAU_SYNTHESE";


-- 	Ajout bénéfice ligne

ALTER TABLE "VENTE_ODS"."TABLEAU_SYNTHESE" ADD COLUMN "BENEFICE" numeric;


UPDATE "VENTE_ODS"."TABLEAU_SYNTHESE"
SET "BENEFICE" = "PRIX_VENTE" - "PRIX_ACHAT";


-- CA par ligne
SELECT 
	tab."ID_CLIENT", 
	tab."DT_VENTE",
	(tab."QTE_VENTE"*tab."PRIX_VENTE") as "CA_LIGNE",
	(tab."QTE_VENTE"*tab."BENEFICE") as "BENEFICE_LIGNE"
FROM "VENTE_ODS"."TABLEAU_SYNTHESE" as tab;

-- CA par client
SELECT TAB."ID_CLIENT",
	SUM(TAB."QTE_VENTE" * TAB."PRIX_VENTE") AS "CA_CLIENT",
	SUM(TAB."QTE_VENTE" * TAB."BENEFICE") AS "BENEFICE_CLIENT"
FROM "VENTE_ODS"."TABLEAU_SYNTHESE" AS TAB
GROUP BY TAB."ID_CLIENT"
ORDER BY "CA_CLIENT" DESC;

-- CA par pays
SELECT TAB."PAYS_CLIENT",
	SUM(TAB."QTE_VENTE" * TAB."PRIX_VENTE") AS "CA_PAYS",
	SUM(TAB."QTE_VENTE" * TAB."BENEFICE") AS "BENEFICE_PAYS"
FROM "VENTE_ODS"."TABLEAU_SYNTHESE" AS TAB
GROUP BY TAB."PAYS_CLIENT"
ORDER BY "CA_PAYS" DESC;

-- CA par sous catégorie
SELECT TAB."LB_SOUS_CATEGORIE",
	SUM(TAB."QTE_VENTE" * TAB."PRIX_VENTE") AS "CA_CATEGORIE",
	SUM(TAB."QTE_VENTE" * TAB."BENEFICE") AS "BENEFICE_CATEGORIE"
FROM "VENTE_ODS"."TABLEAU_SYNTHESE" AS TAB
GROUP BY TAB."LB_SOUS_CATEGORIE"
ORDER BY "CA_CATEGORIE" DESC;